version: 2
jobs:
  build:
    docker:
      - image: opal2/pandoc:0.1

    working_directory: ~/repo

    steps:
      - checkout

      #Compiling md to html
      - run: echo 'export SOURCE_DIR=./src' >> $BASH_ENV
      - run: echo 'export TARGET_DIR=./build' >> $BASH_ENV
      - run: ./scripts/compile_md.sh

      - run: git describe --tags > tag

      - persist_to_workspace:
          root: .
          paths:
            - build
            - tag
            - scripts


  package:
    docker:
      - image: opal2/pandoc:0.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run: mkdir -p /tmp/artifacts
      - run: cd build && tar -czf /tmp/artifacts/privacy-policy-`cat ../tag`.tar.gz *
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts


  deploy:
    docker:
      - image: opal2/pandoc:0.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .

      - run: mkdir -p ~/.ssh && echo $HOST_SSHKEY >> ~/.ssh/known_hosts
      - run: echo 'export FILE=artifacts/privacy-policy-`cat ./tag`.tar.gz' >> $BASH_ENV
      - run: echo 'export DIR=$PRODUCTION_DIR' >> $BASH_ENV
      - run: ./scripts/deploy_tar.sh

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - package:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - deploy:
          requires:
            - package
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
